### ISSUE TITLE
apertium-pol.pol.acx invalid

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-pol#1]
https://github.com/apertium/apertium-spa-pol needs apertium-pol.pol.acx, but the file is invalid. Either one needs adjusting.

**Comment by mr-martian** [comment]
The issue is that the acx file specifies 0 equivalences (changing lttoolbox/acx.rng from `<oneOrMore>` to `<zeroOrMore>` would also fix this)

**Comment by ftyers** [comment]
I added the basic ACX with apostrophes all equivalentised in ae11185.
